# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
