# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161101_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=2035601401, max_length=255, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
