# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20161109_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=255, unique=True, verbose_name='Phone Number'),
        ),
    ]
