# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 00:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20161109_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextForWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=1000)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('entry', models.CharField(max_length=2000)),
                ('emotion_anger', models.CharField(max_length=15)),
                ('emotion_disgust', models.CharField(max_length=15)),
                ('emotion_sadness', models.CharField(max_length=15)),
                ('emotion_fear', models.CharField(max_length=15)),
                ('emotion_joy', models.CharField(max_length=15)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
