# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_contextforweek_personaljournal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Phone Number'),
        ),
    ]
