# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20161114_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='text_active',
            field=models.BooleanField(default=True),
        ),
    ]
