# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_text_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaljournal',
            name='emotion_anger',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='personaljournal',
            name='emotion_disgust',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='personaljournal',
            name='emotion_fear',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='personaljournal',
            name='emotion_joy',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='personaljournal',
            name='emotion_sadness',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
