# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20161127_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaljournal',
            name='context',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.ContextForWeek'),
            preserve_default=False,
        ),
    ]
