# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_reminders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminders',
            name='when',
            field=models.DateField(),
        ),
    ]
